// Shared product data for the entire store.
// Categories: Resin Items, Candles, Keychains, Wall Art, Lippan Art
const allProducts = [
    // Resin Items
    { id: 'ri01', name: 'Resin Ocean Clock', price: 499, category: 'Resin Items', image: 'shopping.webp', description: 'A beautiful wall clock with a resin art ocean wave design.', reviews: [], isNew: true, specifications: { material: 'High-quality Epoxy Resin', dimensions: '12 inches diameter', weight: '450g', color: 'Blue & Teal Ocean Wave', power: '1 AA Battery (not included)', care: 'Wipe clean with soft cloth' } },
    { id: 'ri02', name: 'Resin Photo Frame', price: 349, category: 'Resin Items', image: 'led.webp', description: 'Handmade resin photo frame with custom design.', reviews: [], specifications: { material: 'Epoxy Resin & Wood', dimensions: '8x10 inches', weight: '320g', color: 'Custom Design', frame: 'Wooden Frame Included', care: 'Avoid direct sunlight' } },
    { id: 'ri03', name: 'Resin Coaster Set', price: 299, category: 'Resin Items', image: 'hirn.jpeg', description: 'Set of 6 beautiful resin coasters.', reviews: [], specifications: { material: 'Food-safe Epoxy Resin', dimensions: '4 inches diameter each', weight: '180g (set)', color: 'Assorted Colors', quantity: '6 Pieces', care: 'Hand wash recommended' } },
    { id: 'ri04', name: 'Resin Wall Art', price: 599, category: 'Resin Items', image: 'circular.webp', description: 'Stunning resin art piece for your walls.', reviews: [], specifications: { material: 'Epoxy Resin on Wood Base', dimensions: '14 inches diameter', weight: '650g', color: 'Multi-color Abstract', mounting: 'Ready to Hang', care: 'Dust gently' } },

    // Candles - kraft.4u Collection
    { id: 'cn01', name: 'Scented Candle - Lavender', price: 199, category: 'Candles', image: 'circular.jpeg', description: 'Relaxing lavender scented candle - Handcrafted by kraft.4u', reviews: [], isNew: true, specifications: { material: 'Natural Soy Wax', dimensions: '3 inches diameter x 3.5 inches height', weight: '180g', scent: 'Lavender Essential Oil', burnTime: '35-40 hours', color: 'Natural Cream' } },
    { id: 'cn02', name: 'Decorative Pillar Candle', price: 249, category: 'Candles', image: 'shopping1.webp', description: 'Beautiful decorative pillar candle - kraft.4u exclusive design.', reviews: [], specifications: { material: 'Palm Wax', dimensions: '3 inches diameter x 6 inches height', weight: '350g', color: 'Gradient Peach to Cream', burnTime: '55-60 hours', design: 'Decorative Ripple Pattern' } },
    { id: 'cn03', name: 'Aromatherapy Candle Set', price: 399, category: 'Candles', image: '3panel.webp', description: 'Set of 3 aromatherapy candles - Premium kraft.4u collection.', reviews: [], specifications: { material: 'Natural Soy Wax Blend', dimensions: '2.5 inches diameter x 3 inches each', weight: '150g each', scents: 'Eucalyptus, Lemongrass, Vanilla', burnTime: '30 hours each', quantity: '3 Pieces' } },
    { id: 'cn04', name: 'Hand-poured Soy Candle', price: 299, category: 'Candles', image: 'squarewallpanel.webp', description: 'Natural soy wax hand-poured candle - Made by kraft.4u.', reviews: [], specifications: { material: '100% Natural Soy Wax', dimensions: '3.5 inches diameter x 4 inches height', weight: '250g', scent: 'Custom Blend', burnTime: '45-50 hours', wick: 'Cotton Wick' } },
    { id: 'cn05', name: 'Vanilla Soy Candle', price: 249, category: 'Candles', image: 'shopping.webp', description: 'Sweet vanilla scent hand-poured soy candle - kraft.4u signature.', reviews: [], isNew: true, specifications: { material: 'Natural Soy Wax', dimensions: '3 inches diameter x 3.5 inches height', weight: '200g', scent: 'Pure Vanilla Extract', burnTime: '40-45 hours', color: 'Warm Golden' } },
    { id: 'cn06', name: 'Beeswax Pillar Candle', price: 399, category: 'Candles', image: 'circular.webp', description: 'Natural beeswax pillar candle for a warm glow - kraft.4u handcrafted.', reviews: [], specifications: { material: '100% Pure Beeswax', dimensions: '4 inches diameter x 6 inches height', weight: '500g', color: 'Natural Honey Gold', burnTime: '8-10 hours per inch', feature: 'Dripless Burn' } },
    { id: 'cn07', name: 'Rose Petal Candle', price: 199, category: 'Candles', image: 'peacock.webp', description: 'Beautiful rose petal scented candle - kraft.4u exclusive.', reviews: [], specifications: { material: 'Soy Wax with Real Rose Petals', dimensions: '3 inches diameter x 3 inches height', weight: '160g', scent: 'Rose & Vanilla', burnTime: '35 hours', color: 'Pink with Real Petals' } },
    { id: 'cn08', name: 'Citrus Blast Candle', price: 229, category: 'Candles', image: 'led.webp', description: 'Refreshing citrus aroma candle - kraft.4u signature scent.', reviews: [], specifications: { material: 'Natural Coconut Wax', dimensions: '3.5 inches diameter x 3.5 inches height', weight: '220g', scent: 'Orange, Lemon, Grapefruit', burnTime: '45 hours', color: 'Bright Yellow' } },
    { id: 'cn09', name: 'Lavender Vanilla Set', price: 449, category: 'Candles', image: 'ganesh.webp', description: 'Set of 2 candles - lavender and vanilla scents - kraft.4u collection.', reviews: [], specifications: { material: 'Premium Soy Wax', dimensions: '3 inches diameter x 3.5 inches each', weight: '180g each', scents: 'Lavender & Vanilla', burnTime: '40 hours each', quantity: '2 Pieces' } },
    { id: 'cn10', name: 'Crystal Candle Holder', price: 599, category: 'Candles', image: 'download.png', description: 'Elegant crystal candle holder with decorative candle - kraft.4u premium.', reviews: [], isNew: true, specifications: { material: 'Acrylic Crystal & Soy Wax', dimensions: '4 inches diameter x 6 inches height', weight: '400g', color: 'Clear Crystal with Gold Accent', includes: '_decorative candle included_', design: 'Geometric Crystal Shape' } },
    { id: 'cn11', name: 'Lavender Dreams Candle', price: 279, category: 'Candles', image: 'circular.jpeg', description: 'Premium lavender scented soy candle - kraft.4u handcrafted collection.', reviews: [], isNew: true, specifications: { material: 'Organic Soy Wax', dimensions: '3.5 inches diameter x 4 inches height', weight: '240g', scent: 'French Lavender', burnTime: '50 hours', color: 'Lavender Purple' } },
    { id: 'cn12', name: 'Coconut Wax Candle', price: 349, category: 'Candles', image: 'shopping1.webp', description: 'Pure coconut wax candle with natural oils - kraft.4u eco-friendly.', reviews: [], specifications: { material: 'Coconut Wax & Jojoba Oil', dimensions: '3 inches diameter x 4 inches height', weight: '230g', scent: 'Coconut & Almond', burnTime: '45 hours', feature: 'Vegan & Eco-friendly' } },
    { id: 'cn13', name: 'Spiced Apple Pie Candle', price: 299, category: 'Candles', image: '3panel.webp', description: 'Warm spiced apple pie scent - kraft.4u seasonal favorite.', reviews: [], specifications: { material: 'Natural Soy Wax', dimensions: '3.5 inches diameter x 3.5 inches height', weight: '210g', scent: 'Apple, Cinnamon, Nutmeg', burnTime: '40 hours', color: 'Warm Amber' } },
    { id: 'cn14', name: 'Ocean Breeze Candle', price: 249, category: 'Candles', image: 'squarewallpanel.webp', description: 'Fresh ocean breeze scented candle - kraft.4u signature.', reviews: [], specifications: { material: 'Soy Wax Blend', dimensions: '3 inches diameter x 3.5 inches height', weight: '190g', scent: 'Sea Salt, Jasmine, Musk', burnTime: '38 hours', color: 'Ocean Blue' } },
    { id: 'cn15', name: 'Candle Gift Set Premium', price: 799, category: 'Candles', image: 'peacock.webp', description: 'Luxury candle gift set with 4 premium scents - kraft.4u exclusive.', reviews: [], isNew: true, specifications: { material: 'Premium Soy Wax', dimensions: '2.5 inches diameter x 3 inches each', weight: '140g each', scents: 'Lavender, Vanilla, Rose, Citrus', burnTime: '30 hours each', quantity: '4 Pieces', packaging: 'Luxury Gift Box' } },

    // Keychains
    { id: 'kc01', name: 'Anime Keychain', price: 149, category: 'Keychains', image: 'anime.jpeg', description: 'A beautiful handmade macrame keychain, perfect for your keys or as a bag charm.', reviews: [{ rating: 5, author: 'Jane D.', comment: 'Absolutely beautiful! Great quality.' }, { rating: 4, author: 'John S.', comment: 'Very nice, but a bit smaller than I expected.' }], isNew: true, specifications: { material: 'Cotton Macrame Cord', dimensions: '8 inches length', weight: '25g', color: 'Assorted Anime Colors', closure: 'Silver Metal Clasp', usage: 'Keys, Bags, Wall Decor' } },
    { id: 'kc02', name: 'Cartoon Keychain', price: 149, category: 'Keychains', image: '1.jpg', description: 'A unique keychain made with colored resin and glitter. Each piece is one-of-a-kind.', reviews: [], specifications: { material: 'Epoxy Resin & Glitter', dimensions: '2.5 inches diameter', weight: '35g', color: 'Custom Cartoon Design', closure: 'Silver Ring', feature: 'One of a Kind' } },
    { id: 'kc03', name: 'Couple Keychain', price: 199, category: 'Keychains', image: 'couple.jpg', description: 'A custom keychain with your initial. Made from high-quality acrylic.', reviews: [], specifications: { material: 'Premium Acrylic', dimensions: '3 inches height', weight: '30g', color: 'Custom Name/Initial', personalization: 'Custom Name or Initial', closure: 'Silver Ring' } },
    { id: 'kc04', name: 'Friendship Keychain', price: 119, category: 'Keychains', image: 'friends.jpeg', description: 'A set of two matching keychains, perfect for best friends.', reviews: [], specifications: { material: 'Cotton Cord & Beads', dimensions: '10 inches length each', weight: '40g (pair)', color: 'Matching Set', quantity: '2 Pieces', closure: 'Sliding Knot' } },
{ id: 'kc05', name: 'Evil Eye Keychain', price: 149, category: 'Keychains', image: 'evil-eye.jpeg', description: 'A stylish evil eye keychain to ward off negativity.', reviews: [], specifications: { material: 'Glass Beads & Cotton', dimensions: '4 inches length', weight: '20g', color: 'Blue Evil Eye Design', closure: 'Silver Ring', meaning: 'Protection from Negativity' } },
    { id: 'kc06', name: 'Macrame Keychain', price: 299, category: 'Keychains', image: 'images.jpeg', description: 'Elegant handmade macrame keychain with a leaf design.', reviews: [], specifications: { material: 'Natural Cotton Rope', dimensions: '6 inches length', weight: '35g', color: 'Natural Beige', design: 'Leaf Pattern', closure: 'Brass Ring' } },

    // Wall Art
    { id: 'wa01', name: 'Mandala Wall Art 30cm', price: 499, category: 'Wall Art', image: 'shiv.jpg', description: 'An intricate mandala wall hanging, laser-cut from wood. Adds a spiritual touch to any room.', reviews: [{ rating: 5, author: 'Emily R.', comment: 'Stunning piece, it completely transformed my living room!' }], isNew: true, specifications: { material: 'Laser-cut Plywood', dimensions: '30cm diameter', weight: '450g', color: 'Natural Wood with Gold Paint', mounting: 'Wall Hanging Hook', style: 'Traditional Mandala Design' } },
    { id: 'wa02', name: 'Abstract Canvas Print', price: 499, category: 'Wall Art', image: 'circular.jpeg', description: 'A vibrant abstract canvas print to brighten up your living space. Available in multiple sizes.', reviews: [], specifications: { material: 'Canvas with Wooden Frame', dimensions: '18x24 inches', weight: '600g', print: 'High-quality Digital Print', mounting: 'Ready to Hang', frames: 'Wooden Stretcher Frame' } },
    { id: 'wa03', name: 'Mandala Wall Art 45cm', price: 699, category: 'Wall Art', image: 'circular.webp', description: 'A handmade dream catcher with feathers and beads. Perfect for a bohemian-style bedroom.', reviews: [], specifications: { material: 'Wooden Hoop & Cotton String', dimensions: '45cm diameter', weight: '350g', colors: 'Multi-color with Feathers', components: 'Beads, Feathers, Cotton Thread', style: 'Bohemian Dream Catcher' } },
    { id: 'wa04', name: 'Modern Geometric Art', price: 749, category: 'Wall Art', image: 'hirn.jpeg', description: 'Modern geometric wall art made from reclaimed wood.', reviews: [], specifications: { material: 'Reclaimed Wood', dimensions: '24x36 inches', weight: '1.2kg', color: 'Natural Wood Tones', design: 'Geometric Pattern', mounting: 'Wall Mount Hardware Included' } },
    { id: 'wa05', name: 'LED Photo Display', price: 399, category: 'Wall Art', image: 'led.webp', description: 'A creative way to display your favorite photos with clips and string lights.', reviews: [], specifications: { material: 'Wooden Frame with LED Lights', dimensions: '12x16 inches', weight: '400g', lightSource: 'Warm White LED (USB Powered)', includes: '30 Photo Clips', usage: 'DIY Photo Display' } },

    // Lippan Art (Traditional)
    { id: 'la01', name: 'Circular Lippan Mirror', price: 799, category: 'Lippan Art', image: 'download.jpeg', description: 'Traditional Lippan Kaam (mud and mirror work) from Kutch, Gujarat. A stunning piece of cultural art.', reviews: [], isNew: true, specifications: { material: 'Clay, Mirror & Acrylic Colors', dimensions: '18 inches diameter', weight: '1.5kg', origin: 'Kutch, Gujarat', technique: 'Traditional Lippan Kaam', mounting: 'Wall Mount Ready' } },
    { id: 'la02', name: 'Lippan Art Nameplate', price: 499, category: 'Lippan Art', image: 'shopping1.webp', description: 'A custom-made nameplate for your home featuring beautiful lippan art.', reviews: [], specifications: { material: 'Clay, Mirror & Acrylic', dimensions: '12x6 inches', weight: '800g', personalization: 'Custom Name', origin: 'Handmade in Kutch', mounting: 'Wall Mount with Screws' } },
    { id: 'la03', name: 'Square Wall Panel', price: 799, category: 'Lippan Art', image: 'squarewallpanel.webp', description: 'An elegant square wall panel with detailed mud and mirror work. A true statement piece.', reviews: [], specifications: { material: 'Clay, Mirror Work & Colors', dimensions: '18x18 inches', weight: '1.8kg', design: 'Traditional Geometric Pattern', origin: 'Kutch, Gujarat', mounting: 'Wall Hanging' } },
    { id: 'la04', name: 'Peacock Lippan Art', price: 419, category: 'Lippan Art', image: 'peacock.webp', description: 'A majestic peacock design rendered in traditional Lippan art.', reviews: [], specifications: { material: 'Clay, Mirror & Colors', dimensions: '12x12 inches', weight: '650g', design: 'Peacock Motif', origin: 'Traditional Kutch Art', mounting: 'Wall Ready' } },
    { id: 'la05', name: 'Set of 3 Mini Panels', price: 599, category: 'Lippan Art', image: '3panel.webp', description: 'A set of three small, complementary Lippan art panels to create a gallery wall.', reviews: [], specifications: { material: 'Clay, Mirror Work', dimensions: '6x6 inches each', weight: '450g (set)', design: 'Complementary Patterns', origin: 'Handmade Kutch', quantity: '3 Pieces', mounting: 'Wall Set' } },
    { id: 'la06', name: 'Ganesha Lippan Art', price: 449, category: 'Lippan Art', image: 'ganesh.webp', description: 'An auspicious Ganesha design to bring good fortune to your home.', reviews: [], specifications: { material: 'Clay, Mirror & Acrylic', dimensions: '10x14 inches', weight: '550g', deity: 'Lord Ganesha', origin: 'Traditional Lippan Art', mounting: 'Wall Hanging' } },
];
